firstname = input("Enter your firstname:")
lastname = input("Enter your lastname:")
email = input("Enter your email:")
age = input("Enter your age:")
phone = int(input("Enter your phone number:"))
address = input("Enter your address:")

print("Your firstname is :", firstname)
print("Your lastname is :", lastname)
print("Your email is :", email)
print("Your age is :", age)
print("Your phone is :", phone)
print("Your address is :", address)

print("My name is ", firstname, "", lastname)
